---
- name: Configure SSH
  hosts: CSR1kv
  gather_facts: no
  connection: local

  tasks:
    - name: Create New User Account
      ios_config:
        lines:
          - username admin secret adminpass privilege 15
    
    - name: Configure SSH
      ios_config:
        lines:
          - crypto key generate rsa general-keys modulus 2048
          - ip ssh version 2
          - line vty 0 15
          - transport input ssh
          - login local

    - name: Show IP Interface Brief
      ios_command:
        commands:
          - show running-config | s vty
      register: output

    - name: Save Output to TXT File
      copy: 
        content: "{{ output.stdout[0] }}"
        dest: "ssh-vty-config.txt"
